// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/product_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/product_repo.go -destination=internal/mocks/product_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/proyuen/go-mall/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// CreateSKU mocks base method.
func (m *MockProductRepository) CreateSKU(ctx context.Context, sku *model.SKU) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSKU", ctx, sku)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSKU indicates an expected call of CreateSKU.
func (mr *MockProductRepositoryMockRecorder) CreateSKU(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSKU", reflect.TypeOf((*MockProductRepository)(nil).CreateSKU), ctx, sku)
}

// CreateSPU mocks base method.
func (m *MockProductRepository) CreateSPU(ctx context.Context, spu *model.SPU) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSPU", ctx, spu)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSPU indicates an expected call of CreateSPU.
func (mr *MockProductRepositoryMockRecorder) CreateSPU(ctx, spu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSPU", reflect.TypeOf((*MockProductRepository)(nil).CreateSPU), ctx, spu)
}

// GetSKUByID mocks base method.
func (m *MockProductRepository) GetSKUByID(ctx context.Context, id uint) (*model.SKU, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSKUByID", ctx, id)
	ret0, _ := ret[0].(*model.SKU)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSKUByID indicates an expected call of GetSKUByID.
func (mr *MockProductRepositoryMockRecorder) GetSKUByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSKUByID", reflect.TypeOf((*MockProductRepository)(nil).GetSKUByID), ctx, id)
}

// GetSPUByID mocks base method.
func (m *MockProductRepository) GetSPUByID(ctx context.Context, id uint) (*model.SPU, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSPUByID", ctx, id)
	ret0, _ := ret[0].(*model.SPU)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSPUByID indicates an expected call of GetSPUByID.
func (mr *MockProductRepositoryMockRecorder) GetSPUByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSPUByID", reflect.TypeOf((*MockProductRepository)(nil).GetSPUByID), ctx, id)
}

// ListSPUs mocks base method.
func (m *MockProductRepository) ListSPUs(ctx context.Context, offset, limit int) ([]model.SPU, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSPUs", ctx, offset, limit)
	ret0, _ := ret[0].([]model.SPU)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSPUs indicates an expected call of ListSPUs.
func (mr *MockProductRepositoryMockRecorder) ListSPUs(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSPUs", reflect.TypeOf((*MockProductRepository)(nil).ListSPUs), ctx, offset, limit)
}
